apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  ports:
    - name: localstack-s3-port
      port: 4572
    - name: localstack-sns-port
      port: 4575
    - name: localstack-sqs-port
      port: 4576
    - name: localstack-all-port
      port: 4566
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      hostname: localstack
      containers:
        - image: "localstack/localstack:latest"
          name: localstack
          env:
            - name: SERVICES
              value: "s3,sqs,sns,kms"
            - name: HOSTNAME_EXTERNAL
              value: "localstack"
          ports:
            - containerPort: 4572
            - containerPort: 4575
            - containerPort: 4576
            - containerPort: 4566 # new universal port
