apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: rabbitmq-port
      port: 5672
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
        - image: "rabbitmq:3.7-alpine"
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq_user
            - name: RABBITMQ_DEFAULT_PASS
              value: rabbitmq_password
          ports:
            - containerPort: 5672
