FROM ruby:2.4.3-alpine

# ADD bash.d /root/bash.d
# RUN echo "for f in ~/bash.d/*.sh; do source \$f; done" >> /root/.bashrc

# ADD idle /idle
# RUN chmod a+x /idle

CMD ["/bin/sh", "-c", "while true; do sleep 30; done;"]